-- ██ ███    ██ ██ ████████ 
-- ██ ████   ██ ██    ██    
-- ██ ██ ██  ██ ██    ██    
-- ██ ██  ██ ██ ██    ██    
-- ██ ██   ████ ██    ██    

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "320x1440",
    scale = "1.0",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@144",
    position = "0x0",
    scale = "1.0",
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

-- monitor=,preferred,auto,1,mirror,eDP-1


-- waybar

hl.env("XCURSOR_SIZE", "16")

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.device({
    name = "etps/2-elantech-trackpoint",
    sensitivity = -0.4,
})

hl.window_rule({
    match = {
        class = "^(xwaylandvideobridge)$",
    },
    opacity = 0.0,
    no_anim = true,
    no_initial_focus = true,
    max_size = "1 1",
    no_blur = true,
})

-- ██   ██ ███████ ██    ██ ██████  ██ ███    ██ ██████  ███████ 
-- ██  ██  ██       ██  ██  ██   ██ ██ ████   ██ ██   ██ ██      
-- █████   █████     ████   ██████  ██ ██ ██  ██ ██   ██ ███████ 
-- ██  ██  ██         ██    ██   ██ ██ ██  ██ ██ ██   ██      ██ 
-- ██   ██ ███████    ██    ██████  ██ ██   ████ ██████  ███████ 

local mainMod = "SUPER"

hl.bind("SUPER + R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })

    hl.bind("escape", hl.dsp.submap("reset"))
end)


hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(
    mainMod .. " + SUPER_L",
    hl.dsp.exec_cmd("pkill wofi || wofi --show drun --gtk-dark"),
    { release = true }
)
hl.bind(mainMod .. " + P", hl.dsp.window.pin())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(
    mainMod .. " + SHIFT + F",
    hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" })
)
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprlock"))

local fade_in = "hyprctl keyword animation \"fadeOut,0,0,default\""
local fade_out = "hyprctl keyword animation \"fadeOut,1,4,default\""
local screenshotarea = fade_in .. " ; grimblast --notify copy area; " .. fade_out 
hl.bind("Print", hl.dsp.exec_cmd(screenshotarea))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("grimblast --notify --cursor copy screen"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grimblast --notify --cursor copy output"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("grimblast --notify --cursor copy active"))
hl.bind("ALT + SHIFT + F23", hl.dsp.exec_cmd(screenshotarea))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

--  █████  ██    ██ ██████  ██  ██████          ██                                
-- ██   ██ ██    ██ ██   ██ ██ ██    ██        ██                                 
-- ███████ ██    ██ ██   ██ ██ ██    ██       ██                                  
-- ██   ██ ██    ██ ██   ██ ██ ██    ██      ██                                   
-- ██   ██  ██████  ██████  ██  ██████      ██                                    
-- ██████  ██████  ██  ██████  ██   ██ ████████ ███    ██ ███████ ███████ ███████
-- ██   ██ ██   ██ ██ ██       ██   ██    ██    ████   ██ ██      ██      ██     
-- ██████  ██████  ██ ██   ███ ███████    ██    ██ ██  ██ █████   ███████ ███████
-- ██   ██ ██   ██ ██ ██    ██ ██   ██    ██    ██  ██ ██ ██           ██      ██
-- ██████  ██   ██ ██  ██████  ██   ██    ██    ██   ████ ███████ ███████ ███████

hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
    { locked = true, repeating = true }
)
hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true }
)
hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true }
)
hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SOURCE@ toggle"),
    { locked = true, repeating = true }
)
hl.bind(
    "XF86MonBrightnessUp",
    hl.dsp.exec_cmd("brightnessctl set 10%+"),
    { locked = true, repeating = true }
)
hl.bind(
    "XF86MonBrightnessDown",
    hl.dsp.exec_cmd("brightnessctl set 10%-"),
    { locked = true, repeating = true }
)
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border = "rgba(5294e3ee)",
            inactive_border = "rgba(595959aa)",
        },
        layout = "dwindle",
    },
    input = {
        kb_layout = "us,pt",
        kb_options = "ctrl:swapcaps,grp:win_space_toggle",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
        },
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
    },
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        shadow = {
            enabled = true,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        rounding = 5,
    },
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        preserve_split = true, -- you probably want this
    },
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_status = "master",
    },
})

-- ███████ ████████  █████  ██████  ████████ ██    ██ ██████ 
-- ██         ██    ██   ██ ██   ██    ██    ██    ██ ██   ██
-- ███████    ██    ███████ ██████     ██    ██    ██ ██████ 
--      ██    ██    ██   ██ ██   ██    ██    ██    ██ ██     
-- ███████    ██    ██   ██ ██   ██    ██     ██████  ██     

hl.on("hyprland.start", function()
    -- color temperature depending on time of day
    hl.exec_cmd("wlsunset -l 38.9 -L -9")
    hl.exec_cmd("waybar")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("warp-taskbar")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("brightnessctl set 30%")
    hl.exec_cmd("warp-cli tunnel host add mail.tecnico.ulisboa.pt")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("kitty", { workspace = "1 silent" })
    hl.exec_cmd("kitty", { workspace = "10 silent" })
    hl.exec_cmd(
        "brave --enable-features=TouchpadOverscrollHistoryNavigation,UseOzonePlatform",
        { workspace = "3 silent" }
    )
    hl.exec_cmd("slack", { workspace = "4 silent" })
    hl.exec_cmd("thunderbird", { workspace = "5 silent" })
    hl.exec_cmd("tidal-hifi", { workspace = "9 silent" })
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("hyprpaper")
end)

