general {
    # avoid starting multiple hyprlock instances.
    lock_cmd = pidof hyprlock || hyprlock
    # lock before suspend.
    before_sleep_cmd = loginctl lock-session
    # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = hyprctl dispatch dpms on
}

# dim screen after 2min of inactivity
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# turn off keyboard backlight after 30s of inactivity
listener { 
    timeout = 30
    on-timeout = brightnessctl -sd tpacpi::kbd_backlight set 0
    on-resume = brightnessctl -rd tpacpi::kbd_backlight
}

# lock screen after 5min of inactivity
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# turn screen off after 5.5min of inactivity
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    # screen on when activity is detected after timeout has fired.
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
